// src/app/page.tsx
'use client';

/**
 * VisionPipeline Dashboard
 * 
 * Main dashboard view for the MLOps platform.
 * Displays real-time CV detection, metrics, and system alerts.
 * 
 * Features:
 * - Live stream visualization with bounding boxes
 * - Real-time detection charts
 * - Drift monitoring gauge
 * - Activity heatmap
 * - Class distribution
 * - Alert feed
 */

import React, { useEffect, useState } from 'react';
import { useVisionStream } from '@/hooks/use-vision-stream';
import { useVisionStore } from '@/stores/vision-store';
import { LiveStream } from '@/components/vision/LiveStream';
import { MetricCard } from '@/components/vision/MetricCard';
import { DetectionChart } from '@/components/vision/DetectionChart';
import { DriftGauge } from '@/components/vision/DriftGauge';
import { HeatmapCanvas } from '@/components/vision/HeatmapCanvas';
import { ClassDistribution } from '@/components/vision/ClassDistribution';
import { AlertFeed } from '@/components/vision/AlertFeed';
import { cn } from '@/lib/utils';
import {
  Activity,
  Gauge,
  Wifi,
  WifiOff,
  RefreshCw,
  Video,
  Brain,
  Database,
} from 'lucide-react';

export default function DashboardPage() {
  const {
    isConnected,
    connectionError,
    latestDetections,
    frameNumber,
    inferenceMs,
    fps,
    totalDetections,
    confidenceMean,
    driftScore,
    driftDetected,
    classCounts,
    detectionHistory,
    latencyHistory,
    alerts,
    reconnect,
    clearAlerts,
  } = useVisionStream();

  const { models, activeModelId, setModels } = useVisionStore();

  // Fetch models on mount
  useEffect(() => {
    fetch('/api/v1/models')
      .then(res => res.json())
      .then(data => setModels(data.data || []))
      .catch(console.error);
  }, [setModels]);

  const activeModel = models.find(m => m.id === activeModelId) || models[0];

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-gray-900/80 backdrop-blur-md border-b border-gray-800">
        <div className="max-w-[1600px] mx-auto px-4 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gradient-to-br from-green-500 to-blue-500 rounded-lg">
                <Video className="w-5 h-5" />
              </div>
              <div>
                <h1 className="text-lg font-bold tracking-tight">VisionPipeline</h1>
                <p className="text-xs text-gray-400">Production MLOps Platform</p>
              </div>
            </div>

            <div className="flex items-center gap-4">
              {/* Connection status */}
              <div className="flex items-center gap-2">
                {isConnected ? (
                  <>
                    <Wifi className="w-4 h-4 text-green-400" />
                    <span className="text-xs text-green-400">Connected</span>
                  </>
                ) : (
                  <>
                    <WifiOff className="w-4 h-4 text-red-400" />
                    <span className="text-xs text-red-400">Disconnected</span>
                  </>
                )}
              </div>

              {/* Active model */}
              <div className="flex items-center gap-2 px-3 py-1.5 bg-gray-800 rounded-lg">
                <Brain className="w-4 h-4 text-purple-400" />
                <span className="text-xs text-gray-300">
                  {activeModel ? `${activeModel.name} v${activeModel.version}` : 'YOLOv8n'}
                </span>
              </div>

              {/* Reconnect button */}
              <button
                onClick={reconnect}
                className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
                title="Reconnect"
              >
                <RefreshCw className="w-4 h-4 text-gray-400" />
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Main content */}
      <main className="max-w-[1600px] mx-auto p-4">
        {/* Metrics row */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 mb-4">
          <MetricCard
            label="Active Streams"
            value={1}
            color="green"
          />
          <MetricCard
            label="FPS"
            value={fps}
            unit="/s"
            color="blue"
          />
          <MetricCard
            label="Inference"
            value={inferenceMs.toFixed(1)}
            unit="ms"
            color="amber"
          />
          <MetricCard
            label="Drift Score"
            value={driftScore.toFixed(3)}
            unit="PSI"
            color={driftScore > 0.2 ? 'red' : driftScore > 0.1 ? 'amber' : 'green'}
            alert={driftScore > 0.2}
          />
          <MetricCard
            label="Confidence"
            value={(confidenceMean * 100).toFixed(1)}
            unit="%"
            color="purple"
          />
          <MetricCard
            label="Total Detections"
            value={totalDetections}
            color="green"
          />
        </div>

        {/* Main grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {/* Left column - Live stream */}
          <div className="lg:col-span-2 space-y-4">
            {/* Live stream panel */}
            <div className="bg-gray-900 rounded-xl border border-gray-800 overflow-hidden">
              <div className="flex items-center justify-between px-4 py-3 border-b border-gray-800">
                <h2 className="text-sm font-medium text-gray-200">Live Detection</h2>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-gray-500">Frame #{frameNumber}</span>
                  <div
                    className={cn(
                      'w-2 h-2 rounded-full',
                      isConnected ? 'bg-green-500 animate-pulse' : 'bg-red-500'
                    )}
                  />
                </div>
              </div>
              <div className="p-4">
                <LiveStream
                  detections={latestDetections}
                  fps={fps}
                  inferenceMs={inferenceMs}
                  driftScore={driftScore}
                  width={640}
                  height={480}
                />
              </div>
            </div>

            {/* Detection chart */}
            <div className="bg-gray-900 rounded-xl border border-gray-800 p-4">
              <h2 className="text-sm font-medium text-gray-200 mb-3">
                Detections Over Time
              </h2>
              <DetectionChart data={detectionHistory} height={180} />
            </div>
          </div>

          {/* Right column - Metrics & Alerts */}
          <div className="space-y-4">
            {/* Drift gauge */}
            <div className="bg-gray-900 rounded-xl border border-gray-800 p-4">
              <h2 className="text-sm font-medium text-gray-200 mb-3">
                Model Drift Monitor
              </h2>
              <div className="flex justify-center">
                <DriftGauge score={driftScore} size="lg" />
              </div>
              <div className="mt-3 text-center text-xs text-gray-400">
                {driftScore < 0.1 && 'Model performance is stable'}
                {driftScore >= 0.1 && driftScore < 0.2 && 'Slight drift detected - monitor closely'}
                {driftScore >= 0.2 && driftScore < 0.4 && 'Significant drift - consider retraining'}
                {driftScore >= 0.4 && 'Critical drift - retrain immediately'}
              </div>
            </div>

            {/* Class distribution */}
            <div className="bg-gray-900 rounded-xl border border-gray-800 p-4">
              <h2 className="text-sm font-medium text-gray-200 mb-3">
                Class Distribution
              </h2>
              <ClassDistribution classCounts={classCounts} />
            </div>

            {/* Alert feed */}
            <div className="bg-gray-900 rounded-xl border border-gray-800 p-4">
              <AlertFeed alerts={alerts} onClear={clearAlerts} />
            </div>
          </div>
        </div>

        {/* Bottom row - Heatmap and Latency */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-4">
          {/* Activity heatmap */}
          <div className="bg-gray-900 rounded-xl border border-gray-800 p-4">
            <h2 className="text-sm font-medium text-gray-200 mb-3">
              Activity Heatmap
            </h2>
            <HeatmapCanvas detections={latestDetections} width={640} height={240} />
          </div>

          {/* Latency chart */}
          <div className="bg-gray-900 rounded-xl border border-gray-800 p-4">
            <h2 className="text-sm font-medium text-gray-200 mb-3">
              Inference Latency
            </h2>
            <DetectionChart
              data={latencyHistory.map(d => ({ time: d.time, count: Math.round(d.latency) }))}
              height={180}
            />
          </div>
        </div>

        {/* Architecture info */}
        <div className="mt-6 p-4 bg-gray-900/50 rounded-xl border border-gray-800">
          <h3 className="text-sm font-medium text-gray-200 mb-2">
            Pipeline Architecture
          </h3>
          <div className="flex flex-wrap gap-4 text-xs text-gray-400">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4" />
              <span>Bronze → Silver → Gold Data Lake</span>
            </div>
            <div className="flex items-center gap-2">
              <Brain className="w-4 h-4" />
              <span>YOLOv8 + DeepSORT Tracking</span>
            </div>
            <div className="flex items-center gap-2">
              <Gauge className="w-4 h-4" />
              <span>PSI Drift Detection</span>
            </div>
            <div className="flex items-center gap-2">
              <Activity className="w-4 h-4" />
              <span>WebSocket Real-time</span>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="mt-8 py-4 border-t border-gray-800">
        <div className="max-w-[1600px] mx-auto px-4 flex items-center justify-between text-xs text-gray-500">
          <span>VisionPipeline v1.0.0</span>
          <span>Bronze/Silver/Gold • MLflow • Evidently • WebSocket</span>
        </div>
      </footer>
    </div>
  );
}

// frontend/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import LiveStream from './components/LiveStream.vue';
import { useVisionStream } from './composables/useVisionStream';

const currentView = ref('dashboard');

const selectedStreamId = ref('SIM-001');
const { detections, goldReport, isConnected, error } = useVisionStream(selectedStreamId.value);
</script>

<template>
  <div class="h-screen bg-black text-gray-100 flex flex-col font-sans overflow-hidden">
    
    <!-- Navbar -->
    <header class="h-16 border-b border-gray-800 flex items-center justify-between px-6 bg-gray-900/50 backdrop-blur-md shrink-0">
      <div class="flex items-center gap-3">
        <div class="p-2 bg-blue-500/20 rounded-md border border-blue-500/30">
          <svg class="w-6 h-6 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
          </svg>
        </div>
        <div @click="currentView = 'dashboard'" class="cursor-pointer">
          <h1 class="text-sm font-bold tracking-tight uppercase">VisionPipeline</h1>
          <p class="text-[10px] text-gray-500 font-mono tracking-widest">PRO-GRADE MLOPS CORE</p>
        </div>
      </div>

      <nav class="flex items-center gap-6 text-xs font-medium text-gray-400">
        <button @click="currentView = 'dashboard'" :class="currentView === 'dashboard' ? 'text-white' : 'hover:text-white transition-colors'">DASHBOARD</button>
        <button @click="currentView = 'models'" :class="currentView === 'models' ? 'text-white' : 'hover:text-white transition-colors'">MODELS</button>
        <button @click="currentView = 'logs'" :class="currentView === 'logs' ? 'text-white' : 'hover:text-white transition-colors'">LOGS</button>
        <button @click="currentView = 'alerts'" :class="currentView === 'alerts' ? 'text-white' : 'hover:text-white transition-colors'">ALERTS</button>
      </nav>
      
      <div class="flex items-center gap-3">
        <div class="h-8 w-8 rounded-full bg-gray-800 border border-gray-700 flex items-center justify-center">
          <span class="text-[10px] font-bold">SH</span>
        </div>
      </div>
    </header>

    <!-- Content Router -->
    <main class="flex-1 overflow-auto bg-gray-950">
      
      <!-- DASHBOARD VIEW -->
      <div v-if="currentView === 'dashboard'" class="p-6 h-full grid grid-cols-12 gap-6">
        <!-- Primary Stream Column (8/12) -->
        <section class="col-span-12 lg:col-span-8 flex flex-col gap-6 min-h-[500px]">
          <div class="flex-1 bg-gray-900/40 rounded-xl border border-gray-800/60 p-4">
            <LiveStream 
              :stream-id="selectedStreamId" 
              :detections="detections"
              :is-connected="isConnected"
              :error="error"
            />
          </div>
        </section>

        <!-- Sidebar / Insights Column (4/12) -->
        <aside class="col-span-12 lg:col-span-4 flex flex-col gap-6">
          <!-- PSI Drift Monitor Card -->
          <div class="p-6 bg-gray-900/60 rounded-xl border border-gray-800/80 shadow-lg">
            <div class="flex items-center justify-between mb-4">
              <h3 class="text-xs font-bold text-gray-400 uppercase tracking-widest">Model Drift (PSI)</h3>
              <span 
                class="px-2 py-0.5 rounded text-[10px] font-bold"
                :class="goldReport?.drift_detected ? 'bg-red-500/20 text-red-400' : 'bg-green-500/20 text-green-400'"
              >
                {{ goldReport?.drift_detected ? 'CRITICAL' : 'STABLE' }}
              </span>
            </div>
            
            <div class="flex items-end gap-3 mb-2">
              <span class="text-5xl font-mono font-bold leading-none tracking-tighter">
                {{ goldReport?.psi_score.toFixed(3) || '0.000' }}
              </span>
            </div>
            
            <p class="text-xs text-gray-500 leading-relaxed">
              Status: <span class="text-gray-300">{{ goldReport?.recommendation || 'Analyzing stream...' }}</span>
            </p>

            <div class="mt-4 h-2 bg-gray-800 rounded-full overflow-hidden">
              <div 
                class="h-full transition-all duration-500 ease-out"
                :class="goldReport?.drift_detected ? 'bg-red-500' : 'bg-green-500'"
                :style="{ width: `${Math.min((goldReport?.psi_score || 0) * 100, 100)}%` }"
              ></div>
            </div>
          </div>

          <!-- System Stats -->
          <div class="flex-1 bg-gray-900/40 rounded-xl border border-gray-800/40 border-dashed p-6">
            <h3 class="text-xs font-bold text-gray-400 uppercase tracking-widest mb-6">Pipeline Health</h3>
            <div class="space-y-6">
              <div class="flex items-center justify-between">
                <span class="text-[10px] text-gray-400 font-mono tracking-tighter">BRONZE_INGEST</span>
                <div class="flex items-center gap-2">
                  <div class="w-1.5 h-1.5 rounded-full bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.5)]"></div>
                  <span class="text-[10px] text-gray-300 font-bold">15 FPS</span>
                </div>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-[10px] text-gray-400 font-mono tracking-tighter">SILVER_TRANSFORM</span>
                <div class="flex items-center gap-2">
                  <div class="w-1.5 h-1.5 rounded-full bg-purple-500 shadow-[0_0_8px_rgba(168,85,247,0.5)]"></div>
                  <span class="text-[10px] text-gray-300 font-bold">ACTIVE</span>
                </div>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-[10px] text-gray-400 font-mono tracking-tighter">GOLD_METRICS</span>
                <div class="flex items-center gap-2">
                  <div class="w-1.5 h-1.5 rounded-full bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.5)]"></div>
                  <span class="text-[10px] text-gray-300 font-bold">COMPUTING</span>
                </div>
              </div>
            </div>

            <div class="mt-8 pt-6 border-t border-gray-800/60">
              <p class="text-[10px] text-gray-500 leading-tight mb-2">LAST_DRIVE_EVENT: {{ goldReport?.drift_detected ? 'CRITICAL_LOGGED' : 'AUTO_AUDIT' }}</p>
              <p class="text-[10px] text-gray-500 leading-tight font-mono">HASH: 49e8b_sim_active</p>
            </div>
          </div>
        </aside>
      </div>

      <!-- MODELS VIEW -->
      <div v-else-if="currentView === 'models'" class="p-8">
        <h2 class="text-xl font-bold mb-6">Model Registry</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div v-for="m in ['YOLOv8-Nano-Baseline', 'YOLOv8-Small-Night']" :key="m" class="bg-gray-900 border border-gray-800 p-6 rounded-lg">
            <h4 class="text-blue-400 font-bold mb-2">{{ m }}</h4>
            <div class="text-xs text-gray-500 space-y-1">
              <p>PRECISION: 0.84 mAP</p>
              <p>STATUS: ACTIVE</p>
            </div>
          </div>
        </div>
      </div>

      <!-- LOGS VIEW -->
      <div v-else-if="currentView === 'logs'" class="p-8">
        <h2 class="text-xl font-bold mb-6">Pipeline Logs</h2>
        <div class="bg-gray-900 border border-gray-800 rounded-lg overflow-hidden font-mono text-[10px]">
          <div v-for="l in 10" :key="l" class="p-2 border-b border-gray-800 hover:bg-gray-800/50">
            <span class="text-gray-500">[{{ new Date().toISOString() }}]</span>
            <span class="text-green-500 ml-4">INFO</span>
            <span class="ml-4">Processed frame {{ 1000 + l }} | Detections: 4</span>
          </div>
        </div>
      </div>

    </main>

    <!-- Footer Meta -->
    <footer class="h-8 bg-gray-900/80 border-t border-gray-800 flex items-center px-6 text-[10px] text-gray-600 font-mono gap-6">
      <span>VISION_PIPELINE v0.1.0</span>
      <span>ENGINE: PYTORCH/YOLOV8</span>
      <span>ENCRYPTION: AES-256</span>
      <span class="ml-auto">COPYRIGHT © 2025 SELMA HACI</span>
    </footer>

  </div>
</template>

<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap');

html, body {
  background: black;
  scrollbar-width: thin;
  scrollbar-color: #1f2937 transparent;
}
</style>
